name = "App-winmaildat2tar"
readme_from = "script/winmaildat2tar"
badges = ["travis-ci.com"]
authority = "cpan:UTASHIRO"

module_maker = "ModuleBuildTiny"
static_install = "auto"

[release]
do_not_upload_to_cpan = true

